image: maven:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - visualize
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

code_quality:
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

cache:
  paths:
    - ~/.m2/repository/
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  tags:
    - general

test-nvidia-gpu:
  image: aparapi/aparapi-nvidia:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" != *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report site
    - mv target target-nvidia-gpu
  artifacts:
    when: always
    reports:
      junit:
        - target-nvidia-gpu/surefire-reports/TEST-*.xml
        - target-nvidia-gpu/failsafe-reports/TEST-*.xml
    paths:
      - target-nvidia-gpu
  tags:
    - opencl

test-nvidia-cpu:
  image: aparapi/aparapi-nvidia:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" == *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report site
    - mv target target-nvidia-cpu
  artifacts:
    when: always
    reports:
      junit:
        - target-nvidia-cpu/surefire-reports/TEST-*.xml
        - target-nvidia-cpu/failsafe-reports/TEST-*.xml
    paths:
      - target-nvidia-cpu
  tags:
    - compute

test-amdgpu-cpu:
  image: aparapi/aparapi-amdgpu:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" == *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report site
    - mv target target-amdgpu-cpu
  artifacts:
    when: always
    reports:
      junit:
        - target-amdgpu-cpu/surefire-reports/TEST-*.xml
        - target-amdgpu-cpu/failsafe-reports/TEST-*.xml
    paths:
      - target-amdgpu-cpu
  tags:
    - compute

test-pocl-cpu:
  image: aparapi/aparapi-pocl:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" == *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report site
    - mv target target-pocl-cpu
  artifacts:
    when: always
    reports:
      junit:
        - target-pocl-cpu/surefire-reports/TEST-*.xml
        - target-pocl-cpu/failsafe-reports/TEST-*.xml
    paths:
      - target-pocl-cpu
  tags:
    - compute

coverage:
  stage: visualize # Must be in a stage later than test-jdk11's stage. The visualize stage does not exist by default. Please define it first, or chose an existing stage like deploy.
  image: haynes/jacoco2cobertura:1.0.3
  script:
    - 'python /opt/cover2cover.py target-nvidia-gpu/site/jacoco/jacoco.xml src/main/java > target-nvidia-gpu/site/cobertura.xml'
    - 'python /opt/source2filename.py target-nvidia-gpu/site/cobertura.xml'
    - 'python /opt/cover2cover.py target-nvidia-cpu/site/jacoco/jacoco.xml src/main/java > target-nvidia-cpu/site/cobertura.xml'
    - 'python /opt/source2filename.py target-nvidia-cpu/site/cobertura.xml'
    - 'python /opt/cover2cover.py target-amdgpu-cpu/site/jacoco/jacoco.xml src/main/java > target-amdgpu-cpu/site/cobertura.xml'
    - 'python /opt/source2filename.py target-amdgpu-cpu/site/cobertura.xml'
    - 'python /opt/cover2cover.py target-pocl-cpu/site/jacoco/jacoco.xml src/main/java > target-pocl-cpu/site/cobertura.xml'
    - 'python /opt/source2filename.py target-pocl-cpu/site/cobertura.xml'
  needs: ["test-nvidia-gpu", "test-nvidia-cpu", "test-amdgpu-cpu", "test-pocl-cpu"]
  dependencies:
    - test-nvidia-gpu
    - test-nvidia-cpu
    - test-amdgpu-cpu
    - test-pocl-cpu
  artifacts:
    reports:
      cobertura: target-nvidia-gpu/site/cobertura.xml
      cobertura: target-nvidia-cpu/site/cobertura.xml
      cobertura: target-amdgpu-cpu/site/cobertura.xml
      cobertura: target-pocl-cpu/site/cobertura.xml

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=true deploy
  tags:
    - general
  only:
    - master
    - /^v.*$/
